export const comm = {
  home:"HOME",
  selected:"SELECTES",
  brand:"BRAND",
  settled:"SETTLED",
  chan:"MERCHANTS",
  Contactus:"CONTACT US",
  i18:"English",
  world:"Take you to buy",
  the:"good goods all over the world",
  Android:"download",
  ios:"download",
  text:{
    w_text01:'Surprise Exchange is a full category social e-commerce platform with social circles as the core,integrating global high-quality sources',
    w_text02:'and good goods, and empowering individuals to create value.',
    w_text03:'As a shop owner, you can link your circles with massive preferred goods through your mobile phone.',
    w_text04:'In addition to making more money yourself, you can also make friends and family spend less.',
    w_text05:'As a customer, you can link to the source of massive global high-quality goods through mobile phones and enjoy more favorable prices. ',
  },
  selete:{
    title:"Carefully selected",
    text_01:'Provide users with extremely cost-effective products and directly cooperate with big-name factories and brand foundries,',
    text_02:'to eliminate brand premiums and intermediate links, and select high-quality and cost-effective products for users.',
    namy:"Contains many categories",
    cai:"Direct mining",
    pai:"Word of mouth"
  },
  matrix:"Surprise Exchange Cooperative Brand Matrix",
  click:"One-click",
  than_lyi:"More than 200 million",
  than_yit:"Global users exceed 200 million and continue to grow rapidly",
  chao:"More than 6000",
  chao_h:"More than 6000 brand partners,",
  chao_m:"Cover fashion, beauty, travel, food, home, etc.",
  chao_y:"Lifestyle",
  diversity:"Beautiful Real Diversity",
  spirits:"The three core spirits of Surprise Hui Community,  a unique sho",
  over:"Over 70%",
  after:"After 90, 95 accounted for more than 70%,",
  air:" They are the core dri",
  invite:"Sincerely invite",
  Brand:"1、China Merchants Brand",
  under:" Under the industry breakdown, well-known international and domestic brands, innovative brands, and popular brands in the market that dominate the market share.",
  Merchants:"2、Merchants",
  meet:"It can meet the needs of the users of Surprise Exchange, have a high-cost performance,and share and spread high-quality hot products.If you are also like Surprise,dedicated to creating the best products with the best quality and high-cost performance, please join us.",
  Featured:"精选品",
  StrictAccess:"严准入",
  HighQuality:"高质量",
  CostEffective:"有性价比",
  contact:"contact us",
  Surprise:"Surprise Exchange is a social circle layer as the core",
  Exchange:"A full category social e-commerce platform that empowers individuals to create value.",   
  layer:"Surprise Exchange deeply digs into the advantages of S2B2C model,integrates the world's high-quality supply, cuts off layers of middlemen to make the difference,",
  sharing:"Allow users to enjoy lower-priced high-quality goods and more reasonable revenue sharing through Surprise Exchange.",
  bus:"Business cooperation",
  rights:"Service rights：65415655@.com",
  insurance:"Financial insurance：65415655@.com",
  Business:"Business Cooperation",
  buy:'65415655@.com',
  media:"Media cooperation",
  off:"Surprise member official Weibo",
  wechat:"Surprise member official WeChat",
  food:"Fresh food",
  clothing:"Luggage and clothing",
  makeup:"Beauty makeup",
  appliances:"Furniture appliances"

}